#!/usr/bin/env python3
"""Generate main/src/font_ui_8x16.c (F_UI, UI_DESIGN section 7) from a BDF.

Source font: Spleen 8x16 by Frederic Cambus, BSD 2-Clause.
    https://github.com/fcambus/spleen  (spleen-8x16.bdf)
The table in-tree was generated from Spleen 2.2.0, commit 57f9219, file
sha256 482bdc71e9b490173b283316c9bb8d45285f5e9890d9d9ae0b569948bed9c562.

Usage:
    python tools/gen_font_ui.py path/to/spleen-8x16.bdf > main/src/font_ui_8x16.c

Only printable ASCII (0x20-0x7E) is emitted: 95 glyphs x 16 bytes = 1520
bytes, one byte per row, MSB = leftmost pixel, 1 = ink. The glyphs are used
unmodified; Spleen's stems are already 2 px wide, which is what UI_DESIGN 7
asks for on a 1-bit panel.
"""
import sys

FIRST, LAST = 0x20, 0x7E
W, H = 8, 16

LICENSE = """\
 * Glyph data: Spleen 8x16 2.2.0
 * Copyright (c) 2018-2026, Frederic Cambus
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE."""


def parse_bdf(path):
    glyphs = {}
    enc, rows, in_bitmap, bbx = None, [], False, None
    with open(path, encoding="ascii", errors="replace") as f:
        for line in f:
            line = line.strip()
            if line.startswith("ENCODING "):
                enc = int(line.split()[1])
            elif line.startswith("BBX "):
                bbx = tuple(int(v) for v in line.split()[1:])
            elif line == "BITMAP":
                in_bitmap, rows = True, []
            elif line == "ENDCHAR":
                if enc is not None and FIRST <= enc <= LAST:
                    if bbx != (W, H, 0, -4) or len(rows) != H:
                        sys.exit(f"glyph {enc:#x}: unexpected BBX {bbx} / {len(rows)} rows")
                    glyphs[enc] = rows
                in_bitmap, enc, bbx = False, None, None
            elif in_bitmap:
                rows.append(int(line, 16))
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"missing glyphs: {[hex(c) for c in missing]}")
    return glyphs


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    glyphs = parse_bdf(sys.argv[1])
    out = []
    out.append("// F_UI: 8x16 ASCII font for the e-paper UI (UI_DESIGN 7, #37).")
    out.append("// GENERATED by tools/gen_font_ui.py -- edit the generator, not this file.")
    out.append("/*")
    out.append(LICENSE)
    out.append(" */")
    out.append('#include "font_ui_8x16.h"')
    out.append("")
    out.append("const uint8_t font_ui_8x16[FONT_UI_GLYPHS][FONT_UI_H] = {")
    for c in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{r:02X}" for r in glyphs[c])
        label = "space" if c == 0x20 else ("backslash" if c == 0x5C else chr(c))
        out.append(f"    {{{rows}}}, // 0x{c:02X} {label}")
    out.append("};")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
